### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by ethanopp** [BenBanerjeeRichards/Spotify-history-downloader#1]
@BenBanerjeeRichards I'd love to get this set up and running in my own environment but having some issues with the mongo setup:

```
Looking for config file...
Checking 
Checking config.yml
Found at config.yml
HELLO THERE
HELLO THERE
Got spotify access token
Got spotify access token
Traceback (most recent call last):
  File "C:/Users/Ethan/PycharmProjects/Spotify-history-downloader/main.py", line 121, in <module>
    if __name__ == "__main__": main()
  File "C:/Users/Ethan/PycharmProjects/Spotify-history-downloader/main.py", line 106, in main
    insert(j["items"])
  File "C:/Users/Ethan/PycharmProjects/Spotify-history-downloader/main.py", line 19, in insert
    latest_track = spotify.tracks.find_one({}, sort=[("played_at", pymongo.DESCENDING)])
  File "C:\Users\Ethan\AppData\Local\Programs\Python\Python37\lib\site-packages\pymongo\collection.py", line 1262, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\Ethan\AppData\Local\Programs\Python\Python37\lib\site-packages\pymongo\cursor.py", line 1189, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\Ethan\AppData\Local\Programs\Python\Python37\lib\site-packages\pymongo\cursor.py", line 1104, in _refresh
    self.__send_message(q)
  File "C:\Users\Ethan\AppData\Local\Programs\Python\Python37\lib\site-packages\pymongo\cursor.py", line 982, in __send_message
    helpers._check_command_response(first)
  File "C:\Users\Ethan\AppData\Local\Programs\Python\Python37\lib\site-packages\pymongo\helpers.py", line 155, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: command find requires authentication
```

Does a DB need to be created prior to running the script, and if so where do the credentials get entered? Didn't see anywhere in the config.yml where they would go...

Thanks!

**Comment by BenBanerjeeRichards** [comment]
Ok so this project is a bit of a mess right now and getting it all set up properly is a bit tricky. I plan on making it easier once I'm done with exams. 

It looks like your mongodb has a username and password (mine doesn't as I have it behind a firewall). If I have time later on today I'll see if I can implement username/password support for mongodb.

Quick fix would be to change, in util.py:23, the line 

`client = pymongo.MongoClient(cfg["host"], cfg["port"])`

with 
`client = pymongo.MongoClient("mongodb://{}:{}@{}:{}".format(mongo_username_here,mongo_password_here, cfg["host"], cfg["port"]) `

**Comment by ethanopp** [comment]
Ah okay no worries! One of the other things I needed to do to get this up and running was manually hit the auth api to get my refresh token to set as an environment variable...is it possible to grab that programmatically? Usually it’s just client secret/key that need to be fed

**Comment by BenBanerjeeRichards** [comment]
Yes it is possible, I think I have a script on my laptop somewhere that gets the refresh token so I'll have a look into that

**Comment by BenBanerjeeRichards** [comment]
I've moved away from mongo to sqlite now which should make installation less painful in the future
